function real_features_t = transform_to_real(normalized_features, feature_range)
    % Convert normalized features to real features
    nrows = size(normalized_features,1);

    % Get base features
    real_features = [repelem(feature_range.body_length,nrows)', normalized_features.body_ori, ...
        feature_range.neck_length(1) + normalized_features.neck_length * (feature_range.neck_length(2) - feature_range.neck_length(1)), ...
        feature_range.head_length(1) + normalized_features.head_length * (feature_range.head_length(2) - feature_range.head_length(1)), ...
        feature_range.leg_length(1) + normalized_features.leg_length * (feature_range.leg_length(2) - feature_range.leg_length(1)), ...
        feature_range.tail_length(1) + normalized_features.tail_length * (feature_range.tail_length(2) - feature_range.tail_length(1)), ...
        feature_range.neck_angle(1) + normalized_features.neck_angle * (feature_range.neck_angle(2) - feature_range.neck_angle(1)), ...
        feature_range.head_angle(1) + normalized_features.head_angle * (feature_range.head_angle(2) - feature_range.head_angle(1)), ...
        feature_range.leg_angle(1) + normalized_features.leg_angle * (feature_range.leg_angle(2) - feature_range.leg_angle(1)), ...
        feature_range.tail_angle(1) + normalized_features.tail_angle * (feature_range.tail_angle(2) - feature_range.tail_angle(1))];

    % Create table with appropriate variable names
    var_names = {'body_length','body_ori','neck_length','head_length',...
        'leg_length','tail_length','neck_angle','head_angle','leg_angle','tail_angle'};

    real_features_t = array2table(real_features, 'VariableNames', var_names);
end