likelihood: {}

modules:
  beta_mod:
    class: 'src.Bayesian_state.model.modules.beta.BetaModule'
    kwargs: {
      beta_init: 3.0,
      beta_min: 0.1,
      beta_max: 100.0,
      increase_rate: 1.15,
      decrease_rate: 0.3,
    }
  memory_mod:
    class: 'src.Bayesian_state.model.modules.memory.DualMemoryModule'
    kwargs: {
      w0: 0.8, 
      gamma: 0.8,
    }

agenda:
  - memory_mod
  - beta_mod