likelihood: {}

modules:
  memory_mod:
    class: src.Bayesian_state.model.modules.memory.BayesianMemoryModule
    kwargs: {}
  beta_mod:
    class: 'src.Bayesian_state.model.modules.beta.BetaModule'
    kwargs: {}
  perception_mod:
    class: 'src.Bayesian_state.model.modules.perception.PerceptionModule'

agenda:
  - perception_mod
  - memory_mod
  - beta_mod
