modules:
  perception_mod:
    class: 'src.Bayesian_state.problems.modules.perception.PerceptionModule'
  beta_mod:
    class: 'src.Bayesian_state.problems.modules.beta.BetaModule'
    kwargs: {
      beta_init: 1.0,
      beta_min: 0.1,
      beta_max: 50.0,
      decrease_rate: 0.3,
      correct_additive: 1,
      use_prior_scaling: true,
      prior_beta_scale: 10.0
    }
  hypo_transitions_mod:
    class: 'src.Bayesian_state.problems.modules.hypo_transitions.DynamicHypothesisModule'
    kwargs: {
      "strategies": original_strategies_a,
      "init_num":4,
    } 
  likelihood_mod:
    class: 'src.Bayesian_state.problems.modules.likelihood.LikelihoodModule'
    kwargs: {use_boundary: false}
  memory_mod:
    class: 'src.Bayesian_state.problems.modules.memory.DualMemoryModule'
    kwargs: {
      w0: 0.01, 
      gamma: 0.98,
    }

agenda:
  - perception_mod
  - hypo_transitions_mod
  - likelihood_mod
  - memory_mod
  - beta_mod