modules:
  perception_mod:
    class: 'src.Bayesian_state.problems.modules.perception.PerceptionModule'
  beta_mod:
    class: 'src.Bayesian_state.problems.modules.beta.BetaModule'
    kwargs:
      beta_init: 3.0
      beta_min: 0.1
      beta_max: 100.0
      increase_rate: 1.15
      decrease_rate: 0.3
      correct_additive: 0.5
      use_prior_scaling: true
      prior_beta_scale: 10.0
  hypo_transitions_mod:
    class: 'src.Bayesian_state.problems.modules.hypo_transitions.DynamicHypothesisModule'
    kwargs:
      strategies:
        - {amount: "random_7", method: "random_posterior"}
        - {amount: "fixed", method: "ksimilar_centers", value: 1, proto_hypo_amount: 1, proto_hypo_method: "top", cluster_hypo_method: "top"}
        - {amount: "random_7", method: "random"}
      init_num: 10
  likelihood_mod:
    class: 'src.Bayesian_state.problems.modules.likelihood.LikelihoodModule'
    kwargs: {}
  memory_mod:
    class: 'src.Bayesian_state.problems.modules.memory.DualMemoryModule'
    kwargs:
      w0: null
      gamma: null

agenda:
  - perception_mod
  - hypo_transitions_mod
  - likelihood_mod
  - memory_mod
  - beta_mod
