base:
  k:
    type: int
    default: 0
  beta:
    type: float
    default: 1.0
    bounds: [0.001, 30]
decision:
  phi:
    type: float
    default: 0.5
    bounds: [0.0, 1.]
forget:
  gamma:
    type: float
    default: 1.0
    bounds: [0.0, 1.]