"""Public hypothesis inventory, geometry, and observation-model interfaces."""

from .spaces import (
    BINARY_FAMILY_LABELS,
    CategoryRegion,
    ContinuousHypothesisSpace,
    ContinuousHypothesisSpec,
    DiscreteHypothesisSpace,
    DiscreteHypothesisSpec,
    FAMILY_PAIRED_SUM_ORDER,
    FAMILY_PAIRWISE_ORDER,
    FAMILY_PAIRWISE_SIMILARITY_BAND,
    FAMILY_PAIRWISE_SUM_THRESHOLD,
    FAMILY_PARITY_RULE,
    FAMILY_UNIVARIATE_CENTER_BAND,
    FAMILY_UNIVARIATE_THRESHOLD,
    FrozenParameters,
    Hyperplane,
    Polytope,
    build_continuous_hypothesis_space,
    build_discrete_hypothesis_space,
)
from .geometry import BoundaryGeometry, DiscreteRuleGeometry, PrototypeGeometry
from .observation_model import (
    BasePartition,
    ContinuousPartition,
    DiscreteRulePartition,
    ObservationLikelihood,
)

__all__ = [
    "BINARY_FAMILY_LABELS",
    "BasePartition",
    "BoundaryGeometry",
    "CategoryRegion",
    "ContinuousHypothesisSpace",
    "ContinuousHypothesisSpec",
    "ContinuousPartition",
    "DiscreteHypothesisSpace",
    "DiscreteHypothesisSpec",
    "DiscreteRuleGeometry",
    "DiscreteRulePartition",
    "FAMILY_PAIRED_SUM_ORDER",
    "FAMILY_PAIRWISE_ORDER",
    "FAMILY_PAIRWISE_SIMILARITY_BAND",
    "FAMILY_PAIRWISE_SUM_THRESHOLD",
    "FAMILY_PARITY_RULE",
    "FAMILY_UNIVARIATE_CENTER_BAND",
    "FAMILY_UNIVARIATE_THRESHOLD",
    "FrozenParameters",
    "Hyperplane",
    "ObservationLikelihood",
    "Polytope",
    "PrototypeGeometry",
    "build_continuous_hypothesis_space",
    "build_discrete_hypothesis_space",
]
